import datetime

INFO = {
    "description": "City2CocoStyle",
    "url": "https://github.com/mcahny/pycococreator",
    "version": "0.1.0",
    "year": 2019,
    "contributor": "dahun kim",
    "date_created": datetime.datetime.utcnow().isoformat(' ')
}

LICENSES = [
    {
        "id": 1234,
        "name": " ",
        "url": " "
    }
]
CATEGORIES = [
    {
        'id': 0,
        'name': 'road',
        'supercategory': 'flat',
        'isthing':0,
        'instance_eval':0,
        'trainid':0,
        'ori_id':7,
        'color': [128,64,128],
    },
    {
        'id': 1,
        'name': 'sidewalk',
        'supercategory': 'flat',
        'isthing':0,
        'instance_eval':0,
        'trainid':1,
        'ori_id':8,
        'color': [244,35,232],
    },
    {
        'id': 2,
        'name': 'building',
        'supercategory': 'construction',
        'isthing':0,
        'instance_eval':0,
        'trainid':2,
        'ori_id':11,
        'color': [70,70,70],
    },
    {
        'id': 3,
        'name': 'wall',
        'supercategory': 'construction',
        'isthing':0,
        'instance_eval':0,
        'trainid':3,
        'ori_id':12,
        'color': [102,102,156],
    },
    {
        'id': 4,
        'name': 'fence',
        'supercategory': 'construction',
        'isthing':0,
        'instance_eval':0,
        'trainid':4,
        'ori_id':13,
        'color': [190,153,153],
    },
    {
        'id': 5,
        'name': 'pole',
        'supercategory': 'object',
        'isthing':0,
        'instance_eval':0,
        'trainid':5,
        'ori_id':17,
        'color': [153,153,153],
    },
    {
        'id': 6,
        'name': 'traffic light',
        'supercategory': 'object',
        'isthing':0,
        'instance_eval':0,
        'trainid':6,
        'ori_id':19,
        'color': [250,170,30],
    },
    {
        'id': 7,
        'name': 'traffic sign',
        'supercategory': 'object',
        'isthing':0,
        'instance_eval':0,
        'trainid':7,
        'ori_id':21,
        'color': [220,220,0],
    },
    {
        'id': 8,
        'name': 'vegitation',
        'supercategory': 'nature',
        'isthing':0,
        'instance_eval':0,
        'trainid':8,
        'ori_id':21,
        'color': [107,142,35],
    },
    {
        'id': 9,
        'name': 'terrain',
        'supercategory': 'nature',
        'isthing':0,
        'instance_eval':0,
        'trainid':9,
        'ori_id':22,
        'color': [152,251,152],
    },
    {
        'id': 10,
        'name': 'sky',
        'supercategory': 'sky',
        'isthing':0,
        'instance_eval':0,
        'trainid':10,
        'ori_id':23,
        'color': [70,130,180],
    },
    {
        'id': 11,
        'name': 'person',
        'supercategory': 'human',
        'isthing':1,
        'instance_eval':1,
        'trainid':11,
        'ori_id':24,
        'color': [220,20,60],
    },
    {
        'id': 12,
        'name': 'rider',
        'supercategory': 'human',
        'isthing':1,
        'instance_eval':1,
        'trainid':12,
        'ori_id':25,
        'color': [255,0,0],
    }, 
    {
        'id': 13,
        'name': 'car',
        'supercategory': 'vehicle',
        'isthing':1,
        'instance_eval':1,
        'trainid':13,
        'ori_id':26,
        'color': [0,0,142],
    },
    {
        'id': 14,
        'name': 'truck',
        'supercategory': 'vehicle',
        'isthing':1,
        'instance_eval':1,
        'trainid':14,
        'ori_id':27,
        'color': [0,0,70],
    },
    {
        'id': 15,
        'name': 'bus',
        'supercategory': 'vehicle',
        'isthing':1,
        'instance_eval':1,
        'trainid':15,
        'ori_id':28,
        'color': [0,60,100],
    },
    {
        'id': 16,
        'name': 'train',
        'supercategory': 'vehicle',
        'isthing':1,
        'instance_eval':1,
        'trainid':16,
        'ori_id':31,
        'color': [0,80,100],
    },
    {
        'id': 17,
        'name': 'motorcycle',
        'supercategory': 'vehicle',
        'isthing':1,
        'instance_eval':1,
        'trainid':17,
        'ori_id':32,
        'color': [0,0,230],
    },
    {
        'id': 18,
        'name': 'bicycle',
        'supercategory': 'vehicle',
        'isthing':1,
        'instance_eval':1,
        'trainid':18,
        'ori_id':33,
        'color': [119,11,32],
    },
    
]


# if __name__=="__main__":
#     import json
#     dict_name = 'panoptic_viper_categories.json'
#     with open(dict_name, 'w') as f:
#         json.dump(CATEGORIES,f)
#         